#!/bin/bash

# set -x


sched -p 'gzip -dc ~/cache/trab161/TRC/rtr.trc.gz' \
      -p'gzip -dc ~/cache/trab161/TRC/zip_d.trc.gz' \
      -p'gzip -dc ~/cache/trab161/TRC/zip_e.trc.gz' \
      -p'gzip -dc ~/cache/trab161/TRC/jpeg_e.trc.gz' -q100 -m2000 -c -f | more
